name: Continuous Integration
on:
  push:
    branches: [main]
    paths-ignore: ['*.{md,txt}', build, LICENSE, .*config, .vscode]
    tags-ignore: ['*']
  pull_request:
    branches: ['*']
    paths-ignore: ['*.{md,txt}', build, LICENSE, .*config, .vscode]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build --noEmit

      - name: Lint
        run: yarn lint
